### PR TITLE
Add first tests for cubefittable

### PR DESCRIPTION
**Pull request by felixcremer**
I specified the YAXArrays.MovingWindow, because OnlineStats also exports MovingWindow and if we don't specify the tests depend on the inclusion order in runtests.jl

### CODE REVIEW

**Comment by meggart** [comment]
Thanks for starting this. We have some more extensive tests over at ESDL.jl [here](https://github.com/esa-esdl/ESDL.jl/blob/master/test/online.jl) and [here](https://github.com/esa-esdl/ESDL.jl/blob/master/test/tabletocube.jl) but I guess this is too ESDC-specific so we can't move some of the tests over here?

**Comment by felixcremer** [comment]
I think it is fine to put these tests here. 
How long is the S3Store of the ESDC going to be available? 
Can we fix the path to the S3Store in the tests so that we don't have to pull ESDL.jl as a test dependency?
If we don't want to relay on the ESDC data we could at least copy the structure of these tests and replace the data by artificial data. But I think it is better to test the functionality on real world data.

**Comment by meggart** [comment]
I agree that real-world data would help a lot. However, ESDC-availability might become an issue at one point, so what about switching to some stable netcdf datasets? Like something that unidata provides, or if it has to be Zarr, use CMIP6?

**Comment by felixcremer** [comment]
I think it would be good to do tests on both Zarr and NetCDF datasets, but maybe for a real world test, one dataset would be enough and the other tests could also happen artificial data. 
Do you have some pointers where we would get the CMIP6 data from? Can we download a small subset of the dataset during the continuous testing?

**Review by meggart — APPROVED** [review]

**Pull request merged**
