### PR TITLE
Add an api reference to docs

### PR DESCRIPTION
**Pull request by felixcremer**
This adds autodocs parts to the documentation.
We need to specify every submodule separately, therefore this long module list.

### CODE REVIEW

**Comment by felixcremer** [comment]
You can see a preview of this change here:
https://meggart.github.io/YAXArrays.jl/previews/PR41/api/

**Review by meggart — APPROVED** [review]

**Comment by meggart** [comment]
Very good, thanks. One question: What determines if a function belongs to public or private API? Is it exports? I think there are quite some functions in private which shold actually be in the pulic api (and are exported like CategoricalAxis)

**Comment by felixcremer** [comment]
The public API should be the exported names and the internal api are the not exported names. 
You are right, there is something strange going on. Another example is YAXArray which should also be in the public api. I am going to check this again.

**Comment by felixcremer** [comment]
The functions and types which are missing in the public API but are exported, are exported via reexport and it seems as if this is not picked up by documenter.jl. I am not sure, how we should deal with that. Maybe we can simply export the names also in the submodules.

**Comment by meggart** [comment]
> Maybe we can simply export the names also in the submodules.

Yes, that's a good idea, so we can make each module decide which names need to be exported

**Comment by felixcremer** [comment]
I think, this is good to go for now. At least at a glance, the names which are exported are also listed in the public API. 
In the future I am wondering, whether we should sort this more on a topic basis, but maybe it is also not that important, because this is rather there, that it can be searched for.

**Pull request merged**
